### ISSUE TITLE
 UnicodeDecodeError: 'cp932' codec can't decode byte 0x87 in position 23: illegal multibyte sequence

### ISSUE THREAD

**Issue by hellomyzn** [hellomyzn/subtitle-analysis#7]
# Error
```
Traceback (most recent call last):
  File "/opt/work/main.py", line 27, in <module>
    main()
  File "/opt/work/main.py", line 23, in main
    controller.add()
  File "/opt/work/controllers/subtitle_controller.py", line 36, in add
    subs = self.sub_serv.get_from_srt()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/work/common/decorator/exception_deco.py", line 100, in wrapper
    raise MyException(mes) from exc
common.exceptions.my_exceptions.MyException: SystemException occurred. traceback: Traceback (most recent call last):
   File "/opt/work/common/decorator/exception_deco.py", line 83, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
   File "/opt/work/services/subtitle_service.py", line 44, in get_from_srt
    subs = self.srt_repo.get()
           ^^^^^^^^^^^^^^^^^^^
   File "/opt/work/repositories/subtitles/srt_subtitle_repository.py", line 40, in get
    lines = file.readlines()
            ^^^^^^^^^^^^^^^^
   File "<frozen codecs>", line 322, in decode
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x87 in position 23: invalid start byte
```

**Comment by hellomyzn** [comment]
This is because the file to read was `.DS_Store`
